import { test, expect } from '@playwright/test';

test.describe('GenzyStudio E2E Tests', () => {
  
  test('Dashboard loads correctly', async ({ page }) => {
    await page.goto('http://localhost:5173/');
    await expect(page.locator('h2').first()).toContainText('Dashboard');
  });

  test('Content Composer -> Draft -> Mock Publish flow', async ({ page }) => {
    // 1. Go to Content Composer
    await page.goto('http://localhost:5173/content');
    
    // 2. Fill content
    await page.fill('input[placeholder="Enter an engaging title..."]', 'E2E Test Post');
    await page.fill('textarea[placeholder="What\'s on your mind?"]', 'This is a test post generated by Playwright.');
    
    // 3. Save Draft
    page.on('dialog', dialog => dialog.accept()); // Accept the alert
    await page.click('text=Save Draft');
    
    // 4. Publish
    // The alert gets handled by the previous dialog handler, but we need to wait for the UI to be ready
    await page.waitForTimeout(1000);
    await page.click('text=Review & Publish');
    
    // Check that button shows Publishing or is handled
    await page.waitForTimeout(2000);
  });

  test('Ideas to Content flow', async ({ page }) => {
    await page.goto('http://localhost:5173/ideas');
    
    // Create new idea
    await page.click('text=New Idea');
    await page.fill('input[placeholder="Title"]', 'Playwright Idea');
    await page.fill('textarea[placeholder="Description..."]', 'Testing idea creation');
    await page.click('text=Save');
    
    // Wait for the list to update
    await page.waitForTimeout(1000);
    
    // Convert to content
    await page.click('text=Convert to Content');
    await page.waitForTimeout(1000);
    
    // Verify redirection to content
    await expect(page).toHaveURL(/.*\/content/);
  });

});
